### PR TITLE
css

### PR DESCRIPTION
**Pull request by Getpwnedbydolbajoba**
**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) yes
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes

### CODE REVIEW

**Comment by tom-osborne** [comment]
@Getpwnedbydolbajoba Any previews of what you've changed?

**Comment by Getpwnedbydolbajoba** [comment]
@tom-osborne https://streamable.com/9i25an

**Comment by tom-osborne** [comment]
Not a huge fan of the gradients or animations personally, so I'll let Kakarot decide this one.

**Comment by Rayzer567** [comment]
> Not a huge fan of the gradients or animations personally, so I'll let Kakarot decide this one.

I think I should have put more simple animations these are too much.

**Pull request closed without merging**
