### PR TITLE
Made qb-cityhall Lua, JS and HTML fully translatable

### PR DESCRIPTION
**Pull request by buddizer**
**Describe Pull request**
Made all hard coded text in client/main.lua and server/main.lua translatable with it's variables in english and added spanish translation as well as used i18next framework to translate JavaScript and HTML. Tested and working.

**Questions (please complete the following information):**

Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes
Does your code fit the style guidelines? Yes
Does your PR fit the contribution guidelines? Yes

### CODE REVIEW

**Comment by GhzGarage** [comment]
@buddizer tag me when this is ready for review

**Comment by buddizer** [comment]
@GhzGarage Hi there, this is ready for review

**Comment by GhzGarage** [comment]
> @GhzGarage Hi there, this is ready for review

Has some conflicts now that were for security purposes, just add those for me please

**Comment by buddizer** [comment]
Oh, perfect; was reviewing via my phone and didn't see the merge. Will update this for Tuesday :)

**Comment by buddizer** [comment]
Hi @GhzGarage, I have merged your commits plus fully translated qb-cityhall JavaScript and HTML with i18next framework. Locales for html are under html/locales/en.json and es.json. Tested and working correctly.

**Comment by buddizer** [comment]
Tested and working, if anyone else wants to go ahead and test another language, it would be greatly appreciated.

**Comment by buddizer** [comment]
Can we consider allowing i18next?

**Pull request closed without merging**
