### PR TITLE
Add Job Export

### PR DESCRIPTION
**Pull request by KamuiKody**
this adds an export to add jobs to city hall. I found this convenient since qbcore allows for exports to import jobs. This would allow more outside resources to be easily drag and drop. This adds qb-cityhall as a dependency for anything that calls the export. There is also a check added to see if the job already exists in the table or not. I have tested this a couple times and havent found any issues with it thus far.

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by arsh939 — APPROVED** [review]
The export works perfectly fine!

**Comment by GhzGarage** [comment]
This looks useful but i think there's more to adding the job than just this

**Comment by KamuiKody** [comment]
This is tested working

**Comment by KamuiKody** [comment]
There was an update to make it so you dont have to change half the file anymore to add a job which allows for this to work the way it does

**Pull request merged**
