### PR TITLE
Overhaul

### PR DESCRIPTION
**Pull request by BerkieBb**
https://github.com/qbcore-framework/qb-cityhall/issues/41

### CODE REVIEW

**Comment by webzi** [comment]
When you are going to the cityhall to get your ID card or driving license, you just get "This will not work" error.

**Comment by BerkieBb** [comment]
> When you are going to the cityhall to get your ID card or driving license, you just get "This will not work" error.

Is the cityhall in the config placed in the right spot along with the ped

**Comment by webzi** [comment]
Yeah, the ped is there, and I get the dialog box. I then press on driving license, and then buy. Then I get the this will not work notification
________________________________

**Comment by webzi** [comment]
Just tried to apply for a job aswell.

"Unfortunately will not work" notification comes when trying that.

**Comment by BerkieBb** [comment]
That means it didn't set you in range, are you using the target option?

**Comment by webzi** [comment]
Yeah I'm using the target option

**Comment by BerkieBb** [comment]
I'll take a look after I get home

**Comment by webzi** [comment]
Did you had the time to look at it?

**Comment by milotiro95** [comment]
I had this error code while using this :/ [
Sans titre
](url)

**Comment by BerkieBb** [comment]
> I had this error code while using this :/ [ Sans titre ](url)

That's because you need to download qb-core dev branch

**Comment by BerkieBb** [comment]
@webzi issue fixed

**Comment by IdrisDose** [comment]
Conflicts exist and need updating please.

**Comment by BerkieBb** [comment]
Conflicts fixed

**Comment by GhzGarage** [comment]
has conflicts again

**Comment by BerkieBb** [comment]
Conflicts fixed again

**Comment by BerkieBb** [comment]
> Personally with the version stopped to"chore(config: disable debugPoly) all work fine for me no error, can take a job etc. But I just test you're patch @BerkieBb and the ped from the cityhall isn't spawning anymore (no error server or client side)

I found the issue, by adding `use_fxv2_oal 'yes'` to the fxmanifest.lua, peds don't spawn anymore for some reason, I'm going to find out why now

**Comment by BerkieBb** [comment]
Found the issue, when using OAL, natives can't deserialize certain things like vectors anymore

**Comment by milotiro95** [comment]
Work perfectly now 👍

**Pull request merged**
