### PR TITLE
Add weapons license

### PR DESCRIPTION
**Pull request by Developer-Bear**

### CODE REVIEW

**Comment by BerkieBb** [comment]
This doesn't work for me, I tested it and it gave me an unexpected end of input error on the html, I removed the license from the requestLicenses callback and then it didn't give me the error anymore, in conclusion, the metadata for the weapon license is not set in qb-core and on the player so it will give an error

**Comment by Developer-Bear** [comment]
Did you update cityhall, inventory, and policejob?

**Comment by BerkieBb** [comment]
Yes I know, I check it so much times before commenting

**Comment by Developer-Bear** [comment]
Okay I will look into it tonight. Thanks for testing it

**Comment by Developer-Bear** [comment]
@BerkieBb can I get you to retest at some point? I was also getting those errors, but it was still working. I believe I've resolved the errors now. Should only need to update qb-cityhall if you still have the other PR's on your server

**Comment by BerkieBb** [comment]
I'll test it tomorrow

**Comment by Developer-Bear** [comment]
> I'll test it tomorrow

thanks man

**Pull request merged**
